### ISSUE TITLE
Get rid of "ERROR:omero.gateway:No Pillow installed, line plots and split channel will fail!" message

### ISSUE THREAD

**Issue by manics** [ome/omero-py#11]
```
omero version
ERROR:omero.gateway:No Pillow installed, line plots and split channel will fail!
5.5.1
```
Either:
- Get rid of this message, add pillow to whichever component (omero-web?) requires it.
- Alternatively add Pillow to the required dependencies for this module.

**Comment by will-moore** [comment]
Pillow is now required, so this message is rarely seen now.

**Comment by joshmoore** [comment]
Later option was taken in this repo:

```
    install_requires=[
        'future',
        'numpy',
        'Pillow',
        'zeroc-ice>=3.6.4,<3.7',
    ],

```

Closing this. If someone feels we should remove the warning, either reopen this or just open a PR.
