### ISSUE TITLE
Persisting connections and getting `Ice.ConnectionLostException: Ice.ConnectionLostException: recv() returned zero`

### ISSUE THREAD

**Issue by fireofearth** [ome/omero-py#118]
Specs:
Ubuntu 18.04
Anaconda 3
Python 3.6
zeroc-ice 3.6.5
omero-py commit hash 0b7cc5fcfd773e650cdfddeb557f16db702167a5

I'm currently and all operations listed in <https://docs.openmicroscopy.org/omero-gateway/5.5.3/javadoc/omero/gateway/Gateway.html> is available to me. However I'm unable to persist BlitzGateway connections as I'm getting this error:

```
Ice.ConnectionLostException: Ice.ConnectionLostException: recv() returned zero
```

This error happens in two ways below. Note that this is an issue because I'm using a Flask server as an OMERO client. Any suggestions on persistence will be appreciated.

## way number 1

I have a single BlitzGateway connection. Each time I need to access the connection to do a query I call `BlitzGateway.keepAlive()` which presumably reconnects if the connection is down or timed out. However calling a query beyond the 10 minutes mark after making the last query (i.e. `BlitzGateway.getObjects()` gives the error even if `BlitzGateway.keepAlive()`.

```
# Blitz gateway connection singleton #
__conn = BlitzGateway(USERNAME, PASSWORD, host=HOST, port=PORT)
__conn.connect()

def get_conn():
    __conn.keepAlive()
    return __conn

def refresh_conn():
    __conn.keepAlive()

def close_conn():
    return __conn.close(hard=False)

def get_objects_with_type(t):
    return get_conn().getObjects(t)

def delete_object(t, i):
    return get_conn().deleteObjects(t, [i], deleteAnns=False, deleteChildren=False, wait=True)

# other methods...
```

## way number 2

I now create a new BlitzGateway connection, then connect to it before any query, and close it after the query is done. This only works for the first query. When the second query is called (i.e. another`BlitzGateway.getObjects()` we get that error.

```
def connection(func):
    @functools.wraps(func)
    def wrapper_connection(*args, **kwargs):
        __conn = BlitzGateway(USERNAME, PASSWORD, host=HOST, port=PORT)
        __conn.connect()
        result = func(__conn, *args, **kwargs)
        __conn.close(hard=False)
        return result

    return wrapper_connection

@connection
def get_objects_with_type(conn, t):
    return conn.getObjects(t)

@connection
def delete_object(conn, t, i):
    return conn.deleteObjects(t, [i], deleteAnns=False, deleteChildren=False, wait=True)

# other methods...
```

**Comment by joshmoore** [comment]
> which presumably reconnects if the connection is down or timed out.

It should. The fact that it's not reconnecting is likely a bug.  But the method can (and is intended) to also be called proactively & regularly to keep the client alive. Can you try:

```
__conn.c.enableKeepAlive(timeInSeconds) # 120-300? Certainly less than 600
```

**Comment by fireofearth** [comment]
Thanks @joshmoore, I can potentially try doing that.
For now, it turns out 'way number 2' actually works and was due to a bug on my part: it seems the BlitzObjectWrapper object returned had the BlitzGateway connection bound to it, so accessing the object after the connection closed causes the error.

**Comment by joshmoore** [comment]
Thanks for letting us know!
