### ISSUE TITLE
omero import needs to check for OMERODIR

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-py#161]
If OMERODIR is not set, the following error is printed.

```
09:17:12 + omero import -d Dataset:4851 test.fake --debug ERROR
09:17:13 Cannot get JAR files from '/home/omero/workspace/OMERO-training/omero-virtualenv/lib/lib/client' (No such file or directory)
```

Easy fix: check before running and show the user a helpful message like "Please set OMERODIR".

Harder fix: Automatically download the importer jars.

Workaround: Set OMERODIR :smile:

**Comment by joshmoore** [comment]
The above comes from the OMERO-training job. I renamed the `OMERO_SERVER_DIST` bash variable to be `OMERODIR` correcting the issue.

**Comment by glyg** [comment]
Hi Josh, I have the same error (with the `lib/lib/client` path) when trying to import a directory from a remote client. Is there a quick fix (neither `OMERO_SERVER_DIST` nor `OMERODIR` are set in my environment)? 
omero is version 5.6.2

G.

**Comment by glyg** [comment]
sorry I just need to define OMERODIR - sorry for the noise everything is ok
