### ISSUE TITLE
Cope with MinProtocol = TLSv1.2

### ISSUE THREAD

**Issue by mtbc** [ome/omero-py#250]
https://docs.openmicroscopy.org/omero/5.6.2/sysadmins/unix/server-debian10-ice36.html needs to tweak `/etc/ssl/openssl.cnf` and some experimentation suggests that remains true even with this installed. I wonder if some adjustment to this could make it work around out-of-the-box tighter OpenSSL configuration.

**Comment by jburel** [comment]
I will open a PR later on

**Comment by manics** [comment]
One more thing, can you see if `TLS1_0,TLS1_1,TLS1_2` also works? That includes the current protocol, but hopefully the client will just use whichever one(s) it supports

**Comment by jburel** [comment]
I am planning to test that option

**Comment by jburel** [comment]
see https://github.com/ome/omero-py/pull/251
