### ISSUE TITLE
Overwrite `_repr_html_` for `_ImageWrapper`

### ISSUE THREAD

**Issue by jo-mueller** [ome/omero-py#393]
## Feature pitch: 🖼️ html metadata preview 🖼️ 

Hi all,

I have recently started to work a bit more with OMERO and, more specifically `ompero-py` and `ezomero`. I work predominatly with Jupyter notebooks and what I was often missing, was a clearer visualization of what I had actually just downloaded through the `omero` gateway. And I thought it would be cool if the `_ImageWrapper` object, specifically, had a bit more rich output into a Jupyter notebook than only `<_ImageWrapper id=xyz>`. In other libraries (e.g., dask, vedo, etc), just printing their respective objects shows some nice summaries of some properties of the objects into the notebook. This can be done by overloading the `_repr_html_` method of any class definition.

I started on a little implementation but I first wanted to ask whether it would actually be desirable for you to have this feature before going any further with this. In my current approach, retrieving an image like this:

```
metadata, data = ezomero.get_image(
    conn,
    image_id=some_id,
    no_pixels=True,
    dim_order='tczyx')
```

yields `metadata` and `data`, whereas `data` is `None` and `metadata` is of type `_ImageWrapper`. After overloading `_repr_html_`, simply typing `metadata` in a Jupyter notebook yields this overview:

![Capture](https://github.com/ome/omero-py/assets/38459088/cf106e41-21d6-4257-af14-aab17784e1e2)

In essence, it's a short html document, the values for which are filled with the `self.getName()`, `self.getId()`, etc member functions of the `_ImageWrapper` class. The functionality is only invoked in notebooks, to my knowledge, and should not touch any other functionality.

Looking forward to hearing your thoughts on this and send a PR if you are interested.

Thanks,
Johannes

**Comment by will-moore** [comment]
That sounds like a great idea. Please go ahead and open a PR and we can discuss further there - Thanks!
