### ISSUE TITLE
_repr_html_ in Jupyter fails for objects other than ImageWrapper

### ISSUE THREAD

**Issue by Tom-TBT** [ome/omero-py#435]
Hello,
working with a recent version of omero-py, there is now a nicer looking output for images. 

But for anything else than an image, this produces errors.
The issue in the issue is that they can easily be misinterpreted as mistakes of the user. But the error only comes from `_repr_html_ ` when an object is shown in Jupyter.

![image](https://github.com/user-attachments/assets/1e07afe2-8063-4bbe-81cf-8222fdbb46a0)

The issue is that `_repr_html_` here is implemented for the class `BlitzObjectWrapper`, but the function `image_to_html` only works for images:
https://github.com/ome/omero-py/pull/394/files#diff-a017e360f546e1f25f0118e5c18fd4b4842531636af7903c9c6556309c6d13fbR294-R300

```python
 def _repr_html_(self):
      """
      Returns an HTML representation of the object. This is used by the
      IPython notebook to display the object in a cell.
      """
      return image_to_html(self)
```

I am in favor of using more HTML representations for other kinds of objects, but we should first fix that issue. 

@jo-mueller

**Comment by Tom-TBT** [comment]
Sorry @jo-mueller  for the duplicate. 

I want to push your PR forward, but I just haven't had the time. 
In case I need to change something since you are not available, I'll duplicate your branch and open a new PR.

**Comment by jo-mueller** [comment]
Hi @Tom-TBT , thanks for the reply. I'm back at work for a few hours/week so I can help move the fix forward :)
